export const size = {
  huge: 50,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
};

export const family = {
  Montserrat_Black: 'Montserrat-Black',
  Montserrat_Black_Italic: 'Montserrat-BlackItalic',
  Montserrat_Bold: 'Montserrat-Bold',
  Montserrat_Bold_Italic: 'Montserrat-BoldItalic',
  Montserrat_Extra_Bold: 'Montserrat-ExtraBold',
  Montserrat_Extra_Bold_Italic: 'Montserrat-ExtraBoldItalic',
  Montserrat_Extra_Light: 'Montserrat-ExtraLight',
  Montserrat_Extra_Light_Italic: 'Montserrat-ExtraLightItalic',
  Montserrat_Italic: 'Montserrat-Italic',
  Montserrat_Light: 'Montserrat-Light',
  Montserrat_LightItalic: 'Montserrat-LightItalic',
  Montserrat_Medium: 'Montserrat-Medium',
  Montserrat_Medium_Italic: 'Montserrat-MediumItalic',
  Montserrat_Regular: 'Montserrat-Regular',
  Montserrat_Semi_Bold: 'Montserrat-SemiBold',
  Montserrat_Semi_Bold_Italic: 'Montserrat-SemiBoldItalic',
  Montserrat_Thin: 'Montserrat-Thin',
  Montserrat_ThinItalic: 'Montserrat-ThinItalic',
};
